{% set name = "astroalign" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c2a7046e46bfdc9f629afe10d121713f048221003068c18b0a6888be7283fbf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.6.2
    - python >=3.5
    - scikit-image
    - scipy >=0.15
    - sep

test:
  imports:
    - astroalign

about:
  home: https://astroalign.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A tool to align astronomical images based on asterism matching
  description: |
    ASTROALIGN is a python module that will try to align two stellar
    astronomical images, especially when there is no WCS information available.

    It does so by finding similar 3-point asterisms (triangles) in both images
    and deducing the affine transformation between them.
  doc_url: https://astroalign.readthedocs.io/
  dev_url: https://github.com/toros-astro/astroalign

extra:
  recipe-maintainers:
    - mwcraig
