{% set name = "astroalign" %}
{% set version = "2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f993bdc8346c65b57ff6700c084431b7f870ce9bccc5dbfecf206633de1ea639

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.17
    - python >={{ python_min }}
    - scikit-image
    - scipy >=0.15
    - sep

test:
  imports:
    - astroalign
  requires:
    - python {{ python_min }}

about:
  home: https://astroalign.quatrope.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A tool to align astronomical images based on asterism matching
  description: |
    ASTROALIGN is a python module that will try to align two stellar
    astronomical images, especially when there is no WCS information available.

    It does so by finding similar 3-point asterisms (triangles) in both images
    and deducing the affine transformation between them.
  doc_url: https://astroalign.quatrope.org/
  dev_url: https://github.com/quatrope/astroalign

extra:
  recipe-maintainers:
    - mwcraig
